config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/home', to: "pages#index"
  get '/about', to: "pages#about"
  get '/services', to: "pages#services"
  get '/process', to: "pages#process_page"
  get '/rates', to: "pages#rates"
  get '/contact', to: "pages#contact"
  get '/pay', to: "pages#pay"
  get '/portfolio', to: "portfolios#index"
  get '/portfolio/all', to: "portfolios#all" 
  get '/portfolio/:slug', to: "portfolios#show"

  resources :authors, param: :slug
  resources :books
  resources :genres
  resources :subgenres
  resources :payment_intents, only: [:create]
end

app/views/partials/_author.html.erb
<article class="author">
  <h2>
    <a href="/authors/<%= author.slug %>">
      <%= author.first_name %> <%= author.last_name%>
    </a>
  </h2>
  <% if showTestimonial %>
    <p><%= author.testimonial %></p>
  <% end %>
  <div class="author__image-wrapper">
    <%= image_tag author.featured_book.picture.url, class: "author__image", alt: "The cover of this author's featured book, also a link to their author page" %>
    <a href="/authors/<%= author.slug %>">
      <div class="author__see-more">
        <p>Click here to see all titles for this author.</p>
      </div>
    </a>
  </div>
</article>

app/views/partials/_book.html.erb
<article class="author">
  <h2>
    <a href="/authors/<%= book.author.slug %>">
      <%= book.title %>
    </a>
  </h2>
  <div class="author__image-wrapper">
    <%= image_tag book.picture.url, class: "author__image" %>
    <a href="/authors/<%= book.author.slug %>">
      <div class="author__see-more">
        <p>Click here to see all titles for this author.</p>
      </div>
    </a>
  </div>
</article>

app/views/partials/_sidebar.html.erb
<aside id="sidebar" class="sidebar">
  <h1 class="sidebar-heading"><%= link_to("The Atwater Group", root_path) %></h1>
  <div class="sidebar__brand" style="background: url('<%= image_url("branding/atwater-transparent.png")%>')"></div>
  <p class="sidebar-p">Hi. I am Faith Williams, and as the owner of the Atwater Group, I am dedicated to ensuring you have the best quality work done on your projects.</p>
  <p class="sidebar-p">I have been proofreading all my life - ever since I picked up a book and started to read.</p>
  <p class="sidebar-p"> Check out the <a href="http://theatwatergroup.blogspot.com/">blog</a> for author interviews and helpful hints.</p>
  <nav>
    <ul class="sidebar-menu">
      <li><%= link_to("Home", "/home") %></li>
      <li><%= link_to("About", about_path) %></li>
      <li><%= link_to("Services", services_path) %></li>
      <li><%= link_to("Process", process_path) %></li>
      <li><%= link_to("Portfolio", portfolio_path) %></li>
      <li><%= link_to("Rates", rates_path) %></li>
      <li><%= link_to("Get in touch", contact_path) %></li>
    </ul>
    <div class="social">
      <a href="https://www.facebook.com/TAGProofreading/" data-animate-hover="pulse" class="external facebook social__icon">
        <i class="fa fa-facebook"></i>
      </a>
      <a href="https://twitter.com/FaithProofing" data-animate-hover="pulse" class="external twitter social__icon">
        <i class="fa fa-twitter"></i>
      </a>
      <a href="mailto:fwilliams@theatwatergroup.com" data-animate-hover="pulse" class="email social__icon">
        <i class="fa fa-envelope"></i>
      </a>
      <a href="https://www.linkedin.com/in/faithwilliamstagproofreading/" data-animate-hover="pulse" class="external social__icon">
        <i class="fa fa-linkedin"></i>
      </a>
    </div>
  </nav>
  <div class="copyright">
    <p class="credit">
      &copy;2018 The Atwater Group | Website by <a href="https://ogdenstudios.xyz" target="_blank">Ogden Studios</a>
    </p>
  </div>
  <div class="sidebar__efa" style="background: url('<%= image_url("EFA_logomem_50W.gif")%>')"></div>
</aside>