config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/home', to: "pages#index"
  get '/about', to: "pages#about"
  get '/services', to: "pages#services"
  get '/process', to: "pages#process_page"
  get '/rates', to: "pages#rates"
  get '/contact', to: "pages#contact"
  get '/pay', to: "pages#pay"
  get '/portfolio', to: "portfolios#index"
  get '/portfolio/all', to: "portfolios#all" 
  get '/portfolio/:slug', to: "portfolios#show"

  resources :authors, param: :slug
  resources :books
  resources :genres
  resources :subgenres
  resources :payment_intents, only: [:create]
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books

    def to_param
        slug
      end

      def featured_book 
        self.books.where(featured: true)[0] ? self.books.where(featured: true)[0] : self.books[0]
      end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @slug = "authorPage"
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find_by_slug(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :slug, :featured_author, :testimonial, :website, :full_name, :visible)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<section class="author__form">
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :first_name %>
    <br />
    <%= form.text_field :first_name, id: :author_first_name %>
  </div>
  <div class="field">
    <%= form.label :last_name %>
    <br />
    <%= form.text_field :last_name, id: :author_last_name %>
  </div>
  <div class="field">
    <%= form.label :full_name %>
    <span>(i.e. "Aitken, Elena")</span>
    <br />
    <%= form.text_field :full_name, id: :author_full_name %>
  </div>
  <div class="field">
    <%= form.label :website %>
    <br />
    <%= form.text_field :website, id: :author_website %>
  </div>
  <div class="field">
    <%= form.label :testimonial %>
    <br />
    <%= form.text_area :testimonial, id: :author_testimonial %>
  </div>
  <div class="field">
    <%= form.label :slug %>
    <span>(i.e. "elena-aitken", will be used in URL for each author)</span>
    <br />
    <%= form.text_field :slug, id: :author_slug %>
  </div>
  <div class="field">
    <%= form.label "Featured"%>
    <%= form.check_box :featured_author %>
  </div>
    <div class="field">
    <%= form.label "Visible"%>
    <%= form.check_box :visible %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</section>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> 

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Authors</h1>
<%= link_to 'New Author', new_author_path %>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= author.slug %></td>
        <td><%= link_to 'Show', author_path(slug: author.slug) %></td>
        <td><%= link_to 'Edit', edit_author_path(slug: author.slug) %></td>
        <td><%= link_to 'Destroy', author_path(slug: author.slug), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="book__container">
  <% @author.books.each do |book| %>
    <div class="book">
      <% if current_user && current_user["admin_rights"] == true %>
        <a href="/books/<%= book.id %>">
          <li><%=book.title%></li>
        </a>
      <% else %>
        <li><%=book.title%></li>
      <% end %>
        <div class="author__image-wrapper">
          <%= image_tag book.picture.url, class: "author__image" %>
        </div>
    </div>
  <% end %>
</div>
<% if current_user && current_user["admin_rights"] == true %>
  <%= link_to 'Edit', edit_author_path(@author) %> |
<% end %>