config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/home', to: "pages#index"
  get '/about', to: "pages#about"
  get '/services', to: "pages#services"
  get '/process', to: "pages#process_page"
  get '/rates', to: "pages#rates"
  get '/contact', to: "pages#contact"
  get '/pay', to: "pages#pay"
  get '/portfolio', to: "portfolios#index"
  get '/portfolio/all', to: "portfolios#all" 
  get '/portfolio/:slug', to: "portfolios#show"

  resources :authors, param: :slug
  resources :books
  resources :genres
  resources :subgenres
  resources :payment_intents, only: [:create]
end

app/models/subgenre.rb
class Subgenre < ApplicationRecord
    has_many :books
end

app/controllers/subgenres_controller.rb
class SubgenresController < ApplicationController
  before_action :set_subgenre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :new, :update, :destroy]

  # GET /subgenres
  # GET /subgenres.json
  def index
    @subgenres = Subgenre.all
  end

  # GET /subgenres/1
  # GET /subgenres/1.json
  def show
  end

  # GET /subgenres/new
  def new
    @subgenre = Subgenre.new
  end

  # GET /subgenres/1/edit
  def edit
  end

  # POST /subgenres
  # POST /subgenres.json
  def create
    @subgenre = Subgenre.new(subgenre_params)

    respond_to do |format|
      if @subgenre.save
        format.html { redirect_to @subgenre, notice: 'Subgenre was successfully created.' }
        format.json { render :show, status: :created, location: @subgenre }
      else
        format.html { render :new }
        format.json { render json: @subgenre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subgenres/1
  # PATCH/PUT /subgenres/1.json
  def update
    respond_to do |format|
      if @subgenre.update(subgenre_params)
        format.html { redirect_to @subgenre, notice: 'Subgenre was successfully updated.' }
        format.json { render :show, status: :ok, location: @subgenre }
      else
        format.html { render :edit }
        format.json { render json: @subgenre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subgenres/1
  # DELETE /subgenres/1.json
  def destroy
    @subgenre.destroy
    respond_to do |format|
      format.html { redirect_to subgenres_url, notice: 'Subgenre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subgenre
      @subgenre = Subgenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subgenre_params
      params.fetch(:subgenre, {}).permit(:name, :slug)
    end
end

app/helpers/subgenres_helper.rb
module SubgenresHelper
end

app/views/subgenres/_form.html.erb
<%= form_with(model: subgenre, local: true) do |form| %>
  <% if subgenre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subgenre.errors.count, "error") %> prohibited this subgenre from being saved:</h2>

      <ul>
      <% subgenre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subgenres/edit.html.erb
<h1>Editing Subgenre</h1>

<%= render 'form', subgenre: @subgenre %>

<%= link_to 'Show', @subgenre %> |
<%= link_to 'Back', subgenres_path %>

app/views/subgenres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subgenres</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subgenres.each do |subgenre| %>
      <tr>
        <td><%= link_to 'Show', subgenre %></td>
        <td><%= link_to 'Edit', edit_subgenre_path(subgenre) %></td>
        <td><%= link_to 'Destroy', subgenre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subgenre', new_subgenre_path %>

app/views/subgenres/new.html.erb
<h1>New Subgenre</h1>

<%= render 'form', subgenre: @subgenre %>

<%= link_to 'Back', subgenres_path %>

app/views/subgenres/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subgenre_path(@subgenre) %> |
<%= link_to 'Back', subgenres_path %>